blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discord
    url: https://discord.gg/someengineering
    about: Chat with other users and the Some Engineering team
  - name: ğŸŒ Website
    url: https://some.engineering
    about: Read and search the official Some Engineering website
